owner: Melangebox
repo: status
sites:
  - name: Melangebox
    url: https://melangebox.com
status-website:
  cname: status.melangebox.com
  logoUrl: https://avatars3.githubusercontent.com/u/74049849?s=200&v=4
  name: Melangebox Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
